### ISSUE TITLE
Will also continue to update the CEF?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wjywbs/javacef#20] opened 2015-08-17 03:24 UTC
```
3.1750 version of the CEF is too old
```

Original issue reported on code.google.com by `hl122...@gmail.com` on 11 Aug 2015 at 7:05

**Comment by wjywbs** [comment] 2016-11-03 06:45
Duplicate of #24.

**Closed by wjywbs** 2016-11-03 06:45 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
